baseurl: "" # the subpath of your site
url: "" # the base hostname & protocol for your site, e.g., https:// example.com

exclude:
  - CNAME
  - README.md

include:
  - robots.txt

algolia:
  application_id: O5IRJ16G25
  index_name: dev_sheerid
  nodes_to_index: 'p,li,h1,h2,h3'
  search_only_api_key: a01e1186e2fbbb8d6a7e0805fcfacfcd

future: true

# To update algolia dev_sheerid index manually:
# JEKYLL_ENV=development ALGOLIA_API_KEY='9705708ed8146cc0cd23b2d339cffcad' bundle exec jekyll algolia --config "_config.yml,_config_dev.yml"
